---
apiVersion: v1
kind: Service
metadata:
  name: {{.FEDERATION_DNS_SERVER_DEPLOYMENT_NAME}}
  namespace: {{.FEDERATION_NAMESPACE}}
  labels:
    app: federated-cluster
spec:
  type: LoadBalancer
  selector:
    app: federated-cluster
    module: federation-dns-server
  ports:
    - name: dns
      protocol: UDP
      port: 53
      targetPort: 53
---
apiVersion: v1
kind: Service
metadata:
  name: {{.FEDERATION_DNS_SERVER_DEPLOYMENT_NAME}}-etcd
  namespace: {{.FEDERATION_NAMESPACE}}
  labels:
    app: federated-cluster
spec:
  selector:
    app: federated-cluster
    module: federation-dns-server
  ports:
    - name: etcd
      port: 4001
      targetPort: 4001
